### ISSUE TITLE
How to convert numba.cuda.array to cv2.cuda.GpuMat ?

### ISSUE THREAD

**Issue by flandrewries** [swenkel/opencv_deb_single_package#1]
hello,
I noticed your powerful paper could be used to convert the cv2.cuda.GpuMat to the numba.cuda.array.
https://www.simonwenkel.com/notes/software_libraries/opencv/opencv-cuda-integration.html#integration-with-cupy
If there any way to convert numba.cuda.array to cv2.cuda.GpuMat ?
I've used the default construction method like below, but it not works.

import cv2
import torch
from numba import cuda
test_array = np.random.randn(2, 4, 3)
tensor_gpu = torch.from_numpy(test_array).float().cuda().contiguous()
cuda_array = cuda.as_cuda_array(tensor_gpu[0])   # this is the numba.cuda.array
step =cuda_array.strides[0]
a = cv2.cuda.GpuMat(4, 3, cv2.CV_32FC1, ptr=cuda_array.__cuda_array_interface__['data'][0])   #  this is the cv2.cuda.GpuMat
print(a)

I'm appreciate if you have any good idea about this.
Thanks very much.

**Comment by swenkel** [comment]
Hi, this question is not really related to this repo. To answer your question. As mentioned in my article, it seems to be a one-way street and it seems to work with 2d arrays much easier than with multi dimensional arrays due to vastly different memory layout (it is much easier to understand when reading the C++ sections). The only way I could think of is to allocate a GpuMat, access this GpuMat using e.g. Cupy and copy the values like shown below.


```python
import cv2
import cupy as cp
import numpy as np

class CudaArrayInterface:
    def __init__(self, gpu_mat):
        w, h = gpu_mat.size()
        c = gpu_mat.channels()
        type_map = {
            cv2.CV_8U: "u1", cv2.CV_8S: "i1",
            cv2.CV_16U: "u2", cv2.CV_16S: "i2",
            cv2.CV_32S: "i4",
            cv2.CV_32F: "f4",
            cv2.CV_32FC3:"f4",
            cv2.CV_64F: "f8",
        }
        self.__cuda_array_interface__ = {
            "version": 2,
            "shape": (h, w),
            "data": (gpu_mat.cudaPtr(), False),
            "typestr": type_map[gpu_mat.type()],
            "strides": (gpu_mat.step, gpu_mat.elemSize()),
        }


def main():
    img = cp.random.random((3,3)).astype(cp.float32)
    img_out = np.zeros((3,3)).astype(np.float32)
    img_out_gpumat = cv2.cuda_GpuMat(img_out)
    
    print(img_out_gpumat.download())
    
    
    img_out_cp = cp.asarray(CudaArrayInterface(img_out_gpumat))
    img_out_cp [:,:] = img[:,:]
    
    print(img_out_gpumat.download())


if __name__ == '__main__':
    main()

```

```
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0.76674294 0.03007961 0.8311433 ]
 [0.4843109  0.8307048  0.83404505]
 [0.46953753 0.4791303  0.63209784]]
```
